CREATE TABLE IF NOT EXISTS CLIENTES (
    ID BIGINT PRIMARY KEY auto_increment,
    CPFCNPJ VARCHAR(14),
    UNIQUE (ID)
);

CREATE TABLE IF NOT EXISTS AGENCIAS (
    ID BIGINT PRIMARY KEY auto_increment,
    ENDERECO VARCHAR(255) NOT NULL,
    UNIQUE (ID)
);

CREATE TABLE IF NOT EXISTS CONTAS (
    AGENCIA_ID BIGINT,
    SALDO DOUBLE,
    ATIVA BOOLEAN,
    CLIENTE_ID BIGINT,
    PRIMARY KEY (AGENCIA_ID, CLIENTE_ID),
    FOREIGN KEY (AGENCIA_ID) REFERENCES AGENCIAS(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)

);